<? php
echo '<style>';
echo 'body {';
echo 'font-family: "Helvetica Neue", Helvetica, sans-serif;';
echo '}';
echo '</style>';
echo '';
echo '<img src="https://cdn.discordapp.com/attachments/779463103535906827/779969064902590494/unknown.png" width="100" height="100">';
echo '';
echo '<center>';
echo '<h1>Thank you for submitting your form.';
echo '</h1>';
echo '</center>';
echo '<center>';
echo 'Share this form with others if you want to help veterinarians and pet owners across the world.';
echo '';
echo '';
echo '';
echo '<p>You are appreciated for changing the world for all pet communications.<p>';
echo '';
echo '';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '';
echo '</center>';
echo '';
echo '<b>';
echo 'Press this link to re-submit for another pet:<a href="https://kabraha1.github.io/SyncFiddle--MMhr_Biw3HcptqPIJOT-20201122-094950.html">Pet Application Form</a>';
echo '<br>';
echo 'Press link to see other owners and pets: <a href="https://docs.google.com/spreadsheets/d/e/2PACX-1vRFgmohK10upK5TK8uxZiH36y6wS3O0QVElDQrNvQX0fAcssrKrjCWGp5fgadTNUB1nAoJZYaaMScmZ/pubhtml">Pet Application Google Sheet</a>';
echo '';
echo '';
echo '';
echo '<!background>';
echo '<body style='background-color:#2DEABC';
echo '';
echo '';
echo '';
echo '';
echo '';
echo ';'></body>';
echo '';
echo '<!-- The core Firebase JS SDK is always required and must be listed first -->';
echo '<script src="/__/firebase/8.1.1/firebase-app.js"></script>';
echo '';
echo '<!-- TODO: Add SDKs for Firebase products that you want to use';
echo 'https://firebase.google.com/docs/web/setup#available-libraries -->';
echo '';
echo '<!-- Initialize Firebase -->';
echo '<script src="/__/';
?>